version: '3.0'

expectations:
  population_size: 100000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  # Generate objective 1a dataset
  create_dataset_1a:
    run: stata-mp:latest analysis/cr_dataset_1a.do
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        output: output/cr_dataset_1a.csv

  # Generate objective 1b dataset
  create_dataset_1b:
    run: stata-mp:latest analysis/cr_dataset_1b.do
    needs: [generate_study_population, create_dataset_1a]
    outputs:
      highly_sensitive:
        output: output/cr_dataset_1b.csv

  # Generate objective 1a table
  create_table_1a:
    run: stata-mp:latest analysis/tabulate_1a.do
    needs: [generate_study_population, create_dataset_1a]
    outputs:
      moderately_sensitive:
        output: output/tables/an_table_PublicationDescriptivesTable_1a_redacted.tsv      

  # Generate objective 1b table
  create_table_1b:
    run: stata-mp:latest analysis/tabulate_1b.do
    needs: [generate_study_population, create_dataset_1a, create_dataset_1b]
    outputs:
      moderately_sensitive:
        output: output/tables/an_table_PublicationDescriptivesTable_1b_redacted.tsv      